drop table if exists member cascade;
drop table if exists orders cascade;
drop table if exists goods cascade;

create table goods
(
    id         bigint generated by default as identity,
    name       varchar(255),
    price      integer not null,
    quantity   integer not null,
    seller_id  bigint,
    status     enum ('COMPLETED','ON_SALE','RESERVED'),
    created_at timestamp(6),
    primary key (id)
);
create table member
(
    id       bigint generated by default as identity,
    login_id varchar(255),
    password varchar(255),
    primary key (id)
);
create table orders
(
    id           bigint generated by default as identity,
    price        integer not null,
    quantity     integer not null,
    buyer_id     bigint,
    goods_id     bigint,
    order_status enum ('APPROVED','PENDING_APPROVAL'),
    create_at    timestamp(6),
    primary key (id)
)